### ISSUE TITLE
feat: support latest stable aria roles

### ISSUE THREAD

**Issue by jlp-craigmorten** [guidepup/virtual-screen-reader#2]
# Description

Tracker for upstream issues relating to latest aria roles:

## accname

- [ ] multiple accname failures - updates needed to upstream [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) package
- [ ] `math` element support for testing - update needed to upstream [`jsdom`](https://github.com/jsdom/jsdom) package - https://github.com/jsdom/jsdom/issues/3515

## core-aam

- [ ] multiple skips - updates needed to testing setup to support testing of Accessibility APIs
- [ ] `comment`, `image` role failure - updates needed to upstream [`aria-query`](https://github.com/A11yance/aria-query) package for WAI-ARIA 1.3 roles - https://github.com/A11yance/aria-query/pull/557
- [ ] `deletion`, `insertion`, `mark`, `suggestion` role support for testing - updates needed to [`wpt`](https://github.com/web-platform-tests/wpt) - https://github.com/web-platform-tests/wpt/issues/45779
- [ ] `form` role support for testing - updates needed to [`wpt`](https://github.com/web-platform-tests/wpt) - https://github.com/web-platform-tests/wpt/issues/46924

## dpub-aam

- [ ] multiple skips - updates needed to testing setup to support testing of Accessibility APIs
- [ ] `doc-pagefooter, `doc-pageheader` role failure - updates needed to upstream [`aria-query`](https://github.com/A11yance/aria-query) package - https://github.com/A11yance/aria-query/issues/552

## graphics-aam

Currently not supported

## html-aam

- [ ] multiple contextual role failures - updates needed to upstream [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) package to support roles based on context
- [ ] `hgroup`, `s`, `search` role failures - updates needed to upstream [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) package and upstream [`aria-query`](https://github.com/A11yance/aria-query) package - https://github.com/A11yance/aria-query/issues/553

## svg-aam

- [ ] multiple role and accname failures - updates needed to upstream [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) package

## wai-aria

- [ ] multiple contextual role failures - updates needed to upstream [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) package to support roles based on context
- [ ] `suggestion` role failure - updates needed to upstream [`aria-query`](https://github.com/A11yance/aria-query) package for WAI-ARIA 1.3 roles - https://github.com/A11yance/aria-query/pull/557
- [ ] `img` vs `image` and `directory` vs `list` synonym role failures - updates needed to upstream [`dom-accessibility-api`](https://github.com/eps1lon/dom-accessibility-api) package and upstream [`aria-query`](https://github.com/A11yance/aria-query) package - https://github.com/A11yance/aria-query/pull/557
